kind: Deployment
apiVersion: apps/v1
metadata:
  name: utility
  namespace: utility
  labels:
    app: utility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility
  template:
    metadata:
      labels:
        app: utility
    spec:
      containers:
        - resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          name: utility
          ports:
          image: image-registry.openshift-image-registry.svc:5000/utility/utility1:latest-amd64
          imagePullPolicy: Always
      restartPolicy: Always
      serviceAccount: utility-sa
      serviceAccountName: utility-sa
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
